//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepeatList.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RepeatList.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A clean, simple interface designed for productivity. ähnelt.
        /// </summary>
        public static string A_clean_simple_interface_designed {
            get {
                return ResourceManager.GetString("A_clean_simple_interface_designed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A maximum of %1 synchronised lists are permitted ähnelt.
        /// </summary>
        public static string A_maximum_of_3_synchronised_lists_are_permitted {
            get {
                return ResourceManager.GetString("A_maximum_of_3_synchronised_lists_are_permitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add list ähnelt.
        /// </summary>
        public static string add_list {
            get {
                return ResourceManager.GetString("add_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Items ähnelt.
        /// </summary>
        public static string AddNewItem {
            get {
                return ResourceManager.GetString("AddNewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add new list ähnelt.
        /// </summary>
        public static string AddNewList {
            get {
                return ResourceManager.GetString("AddNewList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An unexpected error has occurred ähnelt.
        /// </summary>
        public static string An_unexpected_error_has_occurred {
            get {
                return ResourceManager.GetString("An_unexpected_error_has_occurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application is closed to update changes ähnelt.
        /// </summary>
        public static string Application_is_closed_to_update_changes {
            get {
                return ResourceManager.GetString("Application_is_closed_to_update_changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure? ähnelt.
        /// </summary>
        public static string Are_you_sure {
            get {
                return ResourceManager.GetString("Are_you_sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Purchase premium subscription 2.99€/month ähnelt.
        /// </summary>
        public static string Buy_Premium_Subscription {
            get {
                return ResourceManager.GetString("Buy_Premium_Subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Buy requests (~700, €1.99) ähnelt.
        /// </summary>
        public static string Buy_requests_099 {
            get {
                return ResourceManager.GetString("Buy_requests_099", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die falten ähnelt.
        /// </summary>
        public static string collapse {
            get {
                return ResourceManager.GetString("collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy list ähnelt.
        /// </summary>
        public static string copy_list {
            get {
                return ResourceManager.GetString("copy_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy list to clipboard ähnelt.
        /// </summary>
        public static string Copy_list_to_clipboard {
            get {
                return ResourceManager.GetString("Copy_list_to_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create ähnelt.
        /// </summary>
        public static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create list ähnelt.
        /// </summary>
        public static string create_list {
            get {
                return ResourceManager.GetString("create_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create new article ähnelt.
        /// </summary>
        public static string Create_new_article {
            get {
                return ResourceManager.GetString("Create_new_article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create Spotify playlist ähnelt.
        /// </summary>
        public static string Create_Spotify_playlist {
            get {
                return ResourceManager.GetString("Create_Spotify_playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete list ähnelt.
        /// </summary>
        public static string Delete_list {
            get {
                return ResourceManager.GetString("Delete_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete synchronisation ähnelt.
        /// </summary>
        public static string Delete_Synchronisation {
            get {
                return ResourceManager.GetString("Delete_Synchronisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to end the synconisation of this list ähnelt.
        /// </summary>
        public static string Do_you_really_want_to_end_the_synchronising_of_this_list {
            get {
                return ResourceManager.GetString("Do_you_really_want_to_end_the_synchronising_of_this_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to use commas (‘,’) as list element separators? ähnelt.
        /// </summary>
        public static string Do_you_want_to_use_commas_as_list_element_separators {
            get {
                return ResourceManager.GetString("Do_you_want_to_use_commas_as_list_element_separators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Done ähnelt.
        /// </summary>
        public static string done {
            get {
                return ResourceManager.GetString("done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Duplicate entries ähnelt.
        /// </summary>
        public static string Duplicate_entries {
            get {
                return ResourceManager.GetString("Duplicate_entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1. enter a list name or 
        ///2. enter a synchronisation key that you have received from someone, e.g. via WhatsApp. ähnelt.
        /// </summary>
        public static string Enter_a_list_name_or_insert_a_ready_made {
            get {
                return ResourceManager.GetString("Enter_a_list_name_or_insert_a_ready_made", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter list name ähnelt.
        /// </summary>
        public static string Enter_list_name {
            get {
                return ResourceManager.GetString("Enter_list_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter many items at once: &quot;apple 1kg; pear; meat 0.5kg&quot;. ähnelt.
        /// </summary>
        public static string Enter_many_items_at_once {
            get {
                return ResourceManager.GetString("Enter_many_items_at_once", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter new list name ähnelt.
        /// </summary>
        public static string Enter_new_list_name {
            get {
                return ResourceManager.GetString("Enter_new_list_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter new position title ähnelt.
        /// </summary>
        public static string Enter_new_position_title {
            get {
                return ResourceManager.GetString("Enter_new_position_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die erweiten ähnelt.
        /// </summary>
        public static string expand {
            get {
                return ResourceManager.GetString("expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export and import full lists as JSON via WhatsApp and work together. ähnelt.
        /// </summary>
        public static string Export_and_import_full_lists_as_JSON {
            get {
                return ResourceManager.GetString("Export_and_import_full_lists_as_JSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export current list ähnelt.
        /// </summary>
        public static string Export_list {
            get {
                return ResourceManager.GetString("Export_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ‘Not completed items’ as a text list ähnelt.
        /// </summary>
        public static string Export_not_completed_as_a_text_list {
            get {
                return ResourceManager.GetString("Export_not_completed_as_a_text_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export to Spotify ähnelt.
        /// </summary>
        public static string Export_to_Spotify {
            get {
                return ResourceManager.GetString("Export_to_Spotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fast Input ähnelt.
        /// </summary>
        public static string FastInput {
            get {
                return ResourceManager.GetString("FastInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Free daily limit reached ähnelt.
        /// </summary>
        public static string Free_daily_limit_reached {
            get {
                return ResourceManager.GetString("Free_daily_limit_reached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Free queries ähnelt.
        /// </summary>
        public static string Free_queries {
            get {
                return ResourceManager.GetString("Free_queries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Help ähnelt.
        /// </summary>
        public static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import/export ähnelt.
        /// </summary>
        public static string Import_export_of_lists {
            get {
                return ResourceManager.GetString("Import_export_of_lists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import list ähnelt.
        /// </summary>
        public static string import_liste {
            get {
                return ResourceManager.GetString("import_liste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import list file ähnelt.
        /// </summary>
        public static string import_liste_file {
            get {
                return ResourceManager.GetString("import_liste_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Input ähnelt.
        /// </summary>
        public static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert: ‘apple’ or: ‘apple;pear;...’ more s.? ähnelt.
        /// </summary>
        public static string InputText_placeholder {
            get {
                return ResourceManager.GetString("InputText_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die POSITION INPUT:
        ///----------------------------------
        ///1. you can use a simple sentence, e.g. ‘Milk 2 pcs’; 
        ///
        ///2. a list as a sentence with a semicolon (‘;’) as a separator, e.g. ‘Milk 2 pcs;Meat 0.5 kg;Juice 1 pack;Bonnen 1 p.’. Such a list can be sent via WhatsApp, for example, and read in quickly.
        ///
        ///3. you can paste a sent list, see point 2, from the clipboard.
        ///
        ///Don&apos;t forget to press the Enter key at the end :)
        ///
        ///MENU ITEM ‘DUPLICATE ITEMS’:
        ///----------------------------------------------------------- [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string InputTextWithMicrophoneViewModel_PlaceholderText {
            get {
                return ResourceManager.GetString("InputTextWithMicrophoneViewModel_PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insufficient credit. Please purchase more to continue using the service. ähnelt.
        /// </summary>
        public static string insufficient_credit {
            get {
                return ResourceManager.GetString("insufficient_credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die List added successfully ähnelt.
        /// </summary>
        public static string List_added_successfully {
            get {
                return ResourceManager.GetString("List_added_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die List information has wrong format ähnelt.
        /// </summary>
        public static string List_information_has_wrong_format {
            get {
                return ResourceManager.GetString("List_information_has_wrong_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die List is empty ähnelt.
        /// </summary>
        public static string List_is_empty {
            get {
                return ResourceManager.GetString("List_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die List ähnelt.
        /// </summary>
        public static string List_manipulation {
            get {
                return ResourceManager.GetString("List_manipulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die List not available or corrupt ähnelt.
        /// </summary>
        public static string List_not_available_or_corrupt {
            get {
                return ResourceManager.GetString("List_not_available_or_corrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die List was imported successfully ähnelt.
        /// </summary>
        public static string List_was_imported_successfully {
            get {
                return ResourceManager.GetString("List_was_imported_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die List was successfully deleted ähnelt.
        /// </summary>
        public static string List_was_successfully_deleted {
            get {
                return ResourceManager.GetString("List_was_successfully_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lists ähnelt.
        /// </summary>
        public static string Lists {
            get {
                return ResourceManager.GetString("Lists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MiniList lets you manage purchases, tasks and notes effortlessly ähnelt.
        /// </summary>
        public static string MiniList_lets_you_manage_purchases {
            get {
                return ResourceManager.GetString("MiniList_lets_you_manage_purchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimal &amp; Intuitive ähnelt.
        /// </summary>
        public static string Minimal_Intuitive {
            get {
                return ResourceManager.GetString("Minimal_Intuitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No application could be found to open the URL ähnelt.
        /// </summary>
        public static string No_application_could_be_found_to_open_the_URL {
            get {
                return ResourceManager.GetString("No_application_could_be_found_to_open_the_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No items to display ähnelt.
        /// </summary>
        public static string No_items_to_display {
            get {
                return ResourceManager.GetString("No_items_to_display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No purchases found ähnelt.
        /// </summary>
        public static string No_purchases_found {
            get {
                return ResourceManager.GetString("No_purchases_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Now select the exported JSON file ‘MiniList_Export.json’, for example from WhatsApp or the file system. Then select the ‘MiniList’ app from the list. The app will close briefly and start automatically after the file has been imported. ähnelt.
        /// </summary>
        public static string Now_select_an_exported_JSON_file_named {
            get {
                return ResourceManager.GetString("Now_select_an_exported_JSON_file_named", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Old entries that begin with the keyword e.g. ‘apple’ (‘apple red 1 kg’, ‘apple green 2 kg’ etc.) are deleted and replaced by new entries. So if you want to keep some variants, please use ‘apple_red 1 kg’, ‘apple_green 2 kg’ etc.
        ///Do you still want to continue? ähnelt.
        /// </summary>
        public static string Old_entries_that_begin_with_the_keyword {
            get {
                return ResourceManager.GetString("Old_entries_that_begin_with_the_keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Only available in the premium version ähnelt.
        /// </summary>
        public static string Only_available_in_the_premium_version {
            get {
                return ResourceManager.GetString("Only_available_in_the_premium_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Operation successfully completed ähnelt.
        /// </summary>
        public static string Operation_successfully_completed {
            get {
                return ResourceManager.GetString("Operation_successfully_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Organize Everything ähnelt.
        /// </summary>
        public static string OrganizeEverything {
            get {
                return ResourceManager.GetString("OrganizeEverything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paste from clipboard ähnelt.
        /// </summary>
        public static string Paste_from_clipboard {
            get {
                return ResourceManager.GetString("Paste_from_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please copy this text to the clipboard and import it via the hamburger menu&gt;&gt;&gt;%1 ähnelt.
        /// </summary>
        public static string Please_copy_this_text_to_the_clipboard_and_import_it_via_the_hamburger_menu {
            get {
                return ResourceManager.GetString("Please_copy_this_text_to_the_clipboard_and_import_it_via_the_hamburger_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please create a first list ähnelt.
        /// </summary>
        public static string Please_create_a_first_list {
            get {
                return ResourceManager.GetString("Please_create_a_first_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter the ID of the list to be synchronised. You will receive this from your partner. ähnelt.
        /// </summary>
        public static string Please_enter_the_ID_of_the_list_to_be_synchronised {
            get {
                return ResourceManager.GetString("Please_enter_the_ID_of_the_list_to_be_synchronised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select the file ‘MiniList_Export.json’ that was sent to you via WhatsApp, for example. ähnelt.
        /// </summary>
        public static string Please_select_the_file_MiniList_Export_json {
            get {
                return ResourceManager.GetString("Please_select_the_file_MiniList_Export_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Positions ähnelt.
        /// </summary>
        public static string Positions {
            get {
                return ResourceManager.GetString("Positions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Premium active ähnelt.
        /// </summary>
        public static string Premium_active {
            get {
                return ResourceManager.GetString("Premium_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Premium feature ähnelt.
        /// </summary>
        public static string premium_feature {
            get {
                return ResourceManager.GetString("premium_feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Premium restored ähnelt.
        /// </summary>
        public static string Premium_restored {
            get {
                return ResourceManager.GetString("Premium_restored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Premium subscription activated ähnelt.
        /// </summary>
        public static string Premium_subscription_activated {
            get {
                return ResourceManager.GetString("Premium_subscription_activated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The purchase failed. Please try again. ähnelt.
        /// </summary>
        public static string Purchase_failed_Try_again {
            get {
                return ResourceManager.GetString("Purchase_failed_Try_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rate app ähnelt.
        /// </summary>
        public static string Rate_app {
            get {
                return ResourceManager.GetString("Rate_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recipe ähnelt.
        /// </summary>
        public static string recipe {
            get {
                return ResourceManager.GetString("recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rename ähnelt.
        /// </summary>
        public static string rename {
            get {
                return ResourceManager.GetString("rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Replace ähnelt.
        /// </summary>
        public static string replace {
            get {
                return ResourceManager.GetString("replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Replace list element when inserting ähnelt.
        /// </summary>
        public static string Replace_old_list_element_when_inserting {
            get {
                return ResourceManager.GetString("Replace_old_list_element_when_inserting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Request synchronisation ähnelt.
        /// </summary>
        public static string Request_synchronisation {
            get {
                return ResourceManager.GetString("Request_synchronisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset current list ähnelt.
        /// </summary>
        public static string Reset_current_list {
            get {
                return ResourceManager.GetString("Reset_current_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset ähnelt.
        /// </summary>
        public static string ResetPositions {
            get {
                return ResourceManager.GetString("ResetPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restore ähnelt.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Say your (shopping) list ähnelt.
        /// </summary>
        public static string Say_your_shopping_list {
            get {
                return ResourceManager.GetString("Say_your_shopping_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search ähnelt.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select a category ähnelt.
        /// </summary>
        public static string Select_a_category {
            get {
                return ResourceManager.GetString("Select_a_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selected list and list synchronisations will now be deleted, do you agree? ähnelt.
        /// </summary>
        public static string Selected_list_and_list_synchronisations_will_now_be_deleted {
            get {
                return ResourceManager.GetString("Selected_list_and_list_synchronisations_will_now_be_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Send synchronisation ähnelt.
        /// </summary>
        public static string Send_synchronisation {
            get {
                return ResourceManager.GetString("Send_synchronisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Setup ähnelt.
        /// </summary>
        public static string setup {
            get {
                return ResourceManager.GetString("setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Share &amp; Collaborate ähnelt.
        /// </summary>
        public static string Share_Collaborate {
            get {
                return ResourceManager.GetString("Share_Collaborate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort by ähnelt.
        /// </summary>
        public static string sort_by {
            get {
                return ResourceManager.GetString("sort_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die By alphabet ähnelt.
        /// </summary>
        public static string sort_by_alphabet {
            get {
                return ResourceManager.GetString("sort_by_alphabet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die By category ähnelt.
        /// </summary>
        public static string sort_by_category {
            get {
                return ResourceManager.GetString("sort_by_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die By date ähnelt.
        /// </summary>
        public static string sort_by_date {
            get {
                return ResourceManager.GetString("sort_by_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die By time ähnelt.
        /// </summary>
        public static string sort_by_time {
            get {
                return ResourceManager.GetString("sort_by_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die String is not a valid list description (JSON format) ähnelt.
        /// </summary>
        public static string String_is_not_a_valid_list_description {
            get {
                return ResourceManager.GetString("String_is_not_a_valid_list_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die String is not a valid List-ID ähnelt.
        /// </summary>
        public static string String_is_not_a_valid_List_ID {
            get {
                return ResourceManager.GetString("String_is_not_a_valid_List_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Success ähnelt.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Synchronisation ähnelt.
        /// </summary>
        public static string Synchronisation {
            get {
                return ResourceManager.GetString("Synchronisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Synchronisation ähnelt.
        /// </summary>
        public static string Synchronisation_of_lists {
            get {
                return ResourceManager.GetString("Synchronisation_of_lists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thank you ähnelt.
        /// </summary>
        public static string Thank_You {
            get {
                return ResourceManager.GetString("Thank You", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thank you for your purchase! ähnelt.
        /// </summary>
        public static string Thank_you_for_your_purchase {
            get {
                return ResourceManager.GetString("Thank_you_for_your_purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The chat response was unsuccessful. Please change the prompt and try again. ähnelt.
        /// </summary>
        public static string The_chat_response_was_unsuccessful {
            get {
                return ResourceManager.GetString("The_chat_response_was_unsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The clipboard is empty ähnelt.
        /// </summary>
        public static string The_clipboard_is_empty {
            get {
                return ResourceManager.GetString("The_clipboard_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The list was saved as a string in the clipboard. This can now be sent via WhatsApp, for example. ähnelt.
        /// </summary>
        public static string The_list_was_saved_as_a_string_in_the_clipboard {
            get {
                return ResourceManager.GetString("The_list_was_saved_as_a_string_in_the_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Credit: %1 ähnelt.
        /// </summary>
        public static string The_remaining_credit_is {
            get {
                return ResourceManager.GetString("The_remaining_credit_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thema ähnelt.
        /// </summary>
        public static string theme {
            get {
                return ResourceManager.GetString("theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This is the link to the published list called &quot;%1&quot;. ähnelt.
        /// </summary>
        public static string This_is_the_link_to_the_published_list_called {
            get {
                return ResourceManager.GetString("This_is_the_link_to_the_published_list_called", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To be able to edit the list ‘%2’, please use the following key: %1 (confidential). ähnelt.
        /// </summary>
        public static string To_be_able_to_edit_the_list_please_use_the_following_key {
            get {
                return ResourceManager.GetString("To_be_able_to_edit_the_list_please_use_the_following_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tokens left ähnelt.
        /// </summary>
        public static string Tokens_left {
            get {
                return ResourceManager.GetString("Tokens_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Undone ähnelt.
        /// </summary>
        public static string undone {
            get {
                return ResourceManager.GetString("undone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown ähnelt.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use MiniList anytime — even without internet. ähnelt.
        /// </summary>
        public static string Use_MiniList_anytime {
            get {
                return ResourceManager.GetString("Use_MiniList_anytime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PREMIUM FEATURE!
        ///Let ChatGPT &amp; Co. create a list for you on your desired topic – whether it&apos;s ‘pizza’, ‘minestrone’, travel ideas, project tasks or something else entirely. You can make three free queries per day. ähnelt.
        /// </summary>
        public static string What_would_you_like_to_create_a_chat_based_list_for {
            get {
                return ResourceManager.GetString("What_would_you_like_to_create_a_chat_based_list_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Works Offline ähnelt.
        /// </summary>
        public static string Works_Offline {
            get {
                return ResourceManager.GetString("Works_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Would you like to overwrite the existing list with new data? ähnelt.
        /// </summary>
        public static string Would_you_like_to_overwrite_the_existing_list_with_new_data {
            get {
                return ResourceManager.GetString("Would_you_like_to_overwrite_the_existing_list_with_new_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Would you like to start synchronisation now? ähnelt.
        /// </summary>
        public static string Would_you_like_to_start_synchronisation_now {
            get {
                return ResourceManager.GetString("Would_you_like_to_start_synchronisation_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Would you like to work with someone on a current list? ähnelt.
        /// </summary>
        public static string Would_you_like_to_work_with_someone_on_a_current_list {
            get {
                return ResourceManager.GetString("Would_you_like_to_work_with_someone_on_a_current_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your text appears here... ähnelt.
        /// </summary>
        public static string Your_text_appears_here {
            get {
                return ResourceManager.GetString("Your_text_appears_here", resourceCulture);
            }
        }
    }
}
